### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jeremybarbet** [ueno-llc/template-www#2]
## Template-www
- [x] Add readme to this repo, and remove it after installed completed from create-ueno-app
- [x] Add reset-paragraph to reset
- [x] Clean colors from variables
- [x] Clean button components, non-used props
- [x] Add cmd+g shortcut to enable gsap tools
- [x] Change z-index of devtools (> 10000)
- [x] Remove scale-font by default and move it to a mixin with boolean
- [x] Move the helmet config to external file to make it simpler
- [x] Add meta/colors/og-image to helmet default config

## Next/CRA/Gatsby
- [x] Add `@types/gsap`
- [x] Add `lodash`
- [x] Clean types without dependencies
- [x] Allow `.env.example` (.gitignore now)
- [ ] Add google analytics?
- [ ] HMR broken

## GsapTools
- [x] Add index.d.ts
